version: '3.3'
services:

  nuve_docs:
    container_name: nvue_docs
    restart: always
    build:
      dockerfile: Dockerfile
    image: nvue_docs
    volumes:
      - ./nuve-docs/home:/home
    ports:
      - 3000:80
    # privileged: true