version: '3.3'
services:

  nuve_docs:
    container_name:  nuve_docs
    restart: always
    build:
      dockerfile: Dockerfile
    image:  manjunath777rgowda/nuve_docs
    volumes:
      - ./nuve-docs/home:/home
    ports:
      - 3000:80
    # privileged: true